### ISSUE TITLE
Bittorrent V2 Support

### ISSUE THREAD

**Issue by Adrian-at-CrimsonAuzre** [gallexis/pytorrent#12]
Does this library support the [Bittorrent V2](https://blog.libtorrent.org/2020/09/bittorrent-v2/)/[BEP 52](http://bittorrent.org/beps/bep_0052.html) protocol? If not, I would like to make this a feature request.

I may dive into the library and help submit PRs if this is something that is deemed worth supporting.

**Comment by gallexis** [comment]
Hello, this library does not support the new Bittorrent V2, but it would be very cool if someone could do it. 
Please just keep in mind this repo is made for learning so we should keep the code as simple and clear as possible :)
