### ISSUE TITLE
Bytes input of list of peers is not handled in tracker.py

### ISSUE THREAD

**Issue by SHUNYA007** [gallexis/pytorrent#13]
There can be a case where the list of peers in the response from the tracker can be of bytes form instead of dictionary. 
`s = SockAddr(p['ip'], p['port'])` in the tracker.py will produce [TypeError.)

**Comment by SHUNYA007** [comment]
Created a pull request to fix this error i hope u can merge this thank you.

**Comment by gallexis** [comment]
Thanks, I will look at it 👍

**Comment by gallexis** [comment]
Good job, thanks
