### ISSUE TITLE
Could you provide some .torrent files as examples? 

### ISSUE THREAD

**Issue by YanShulinjj** [gallexis/pytorrent#17]
hello,  I use my own torrent file to test the code, but something wrong like this:
   File "F:\研究生\分布式系统\pytorrent-master\pytorrent-master\peers_manager.py", line 96, in run
    read_list, _, _ = select.select(read, [], [], 1)
OSError: [WinError 10022] 提供了一个无效的参数(valid argument has provided, in English)。

I guess my own file may cause this error.

**Comment by gallexis** [comment]
Hello, PyTorrent does not work on Windows, see in the readme :
"💥 Because it's using the "select" function, this code will not be able to run on Windows: [python-select-on-windows](https://stackoverflow.com/a/22254123/3170071)"
