### ISSUE TITLE
No way to provide torrent file from command line

### ISSUE THREAD

**Issue by Mys7erio** [gallexis/pytorrent#23]
There's no quick way to run the program by providing the torrent file from the command line itself.

Right now,  the name of the torrent file is hard-coded which is considered bad practice. Using the sys module to take the torrent file name as an argument from the command line would be a quick fix and a QOL upgrade.

**Comment by gallexis** [comment]
Good job thank you, I merged a bit too fast as we didn't modify the ReadMe
