### ISSUE TITLE
addon to kodi

### ISSUE THREAD

**Issue by zoreu** [gallexis/pytorrent#27]
do you intend to create a kodi addon using pytorrent? would be good for xbox one
elementum is no longer developed and the binary does not run on xbox one, so pytorrent can revolutionize kodi.

**Comment by gallexis** [comment]
Hello, pytorrent is not really maintained anymore plus it was only madefor educationnal purpose only to understand how the BitTorrent network works using Python.
But feel free to fork it or create your own project based on it! :)
