### ISSUE TITLE
seeding

### ISSUE THREAD

**Issue by AnkiKong** [gallexis/pytorrent#6]
Does the project support NAT? I have tried seeding, but I found the message with correct IP but without correct PORT(always 8000) from tracker

**Comment by gallexis** [comment]
I have tested it through a few different NAT networks and it worked, but I haven't tested it further.

**Comment by AnkiKong** [comment]
> I have tested it through a few different NAT networks and it worked, but I haven't tested it further.

Are you running on a computer with a public IP？

**Comment by gallexis** [comment]
No I am behind a NAT

**Comment by gallexis** [comment]
I'm sorry I don't have much time to help you right know, did you find any solution?

**Comment by AnkiKong** [comment]
sorry, i am busy preparing the final exam these days, later maybe work for this.

**Comment by gallexis** [comment]
I'm closing this issue, you can reopen it if you think there is still a problem
