### ISSUE TITLE
INFO:root:No unchocked peers

### ISSUE THREAD

**Issue by thilanka** [gallexis/pytorrent#7]
After putting the torrent file like below,

```
self.torrent = torrent.Torrent().load_from_path(
            "ubuntu-18.04.4-desktop-amd64.iso.torrent")
```
I only get the INFO:root:No unchocked peers in the terminal.
No download is happening.
Thanks.

**Comment by gallexis** [comment]
You might have to wait a bit longer, you can set the logging to "DEBUG" if you want to see more of what's happening.
logging.basicConfig(level=logging.DEBUG)

**Comment by thilanka** [comment]
added debug logging and tried again for around 30 minutes. still the same message.
`DEBUG:root:[['https://torrent.ubuntu.com/announce'], ['https://ipv6.torrent.ubuntu.com/announce']]
DEBUG:root:[{'path': 'ubuntu-18.04.4-desktop-amd64.iso', 'length': 2126544896}]
INFO:root:PeersManager Started
INFO:root:PiecesManager Started
INFO:root:Trying to connect to 0 peer(s)`

**Comment by gallexis** [comment]
Should be fixed, scraping from a http tracker was commented out in the code (and buggy)

**Comment by thilanka** [comment]
what should i do to avoid http tracker. I need to make his work. Thanks.

**Comment by gallexis** [comment]
You can pull from master and try again, I have updated the code

**Comment by thilanka** [comment]
While the speed is not to the expectation I get this error in between.
`ERROR:root:Error when unpacking message
Traceback (most recent call last):
  File "/app/pytorrent/message.py", line 24, in dispatch
    payload_length, message_id, = unpack(">IB", self.payload[:5])
struct.error: unpack requires a buffer of 5 bytes
Number of peers: 8 - Completed : 3.74% | Got 0/4057 pieces
Number of peers: 8 - Completed : 3.75% | Got 0/4057 pieces
Number of peers: 8 - Completed : 3.75% | Got 0/4057 pieces
`
Thanks. Can the speed be improved?

**Comment by gallexis** [comment]
I have improved the logs but this error can happen if a packet is malformed, maybe because I don't handle it properly or for whatever other reason. Anyway it should not be a big deal since it will retry again later so you should be able to download the rest of the pieces. I don't have time to do some further debugging but feel free to send me a PR if you find something.
